[tools]
gitleaks = "latest"
hk = "latest"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
trufflehog = "latest"
chezmoi = "latest"
#prettier = "latest" # mise os detection is broken on windows

[env]
HK_LIBGIT2 = 0
HOST_SSH = "ssh chris@192.168.1.236"
HOST_REPO = "/users/chris/unattend"
