[settings]
env_shell_expand = true

[tools]
hk = "latest"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
oxfmt = "latest"
shellharden = "latest"

[env]
REPO = "{{ config_root | absolute }}"
REPO_NAME = "{{ config_root | basename }}"

HOST_SSH = "ssh chris@192.168.1.32"
HOST_REPO = "/users/chris/unattend"

[tasks.fix]
alias = 'f'
run = 'hk fix --all'
